repos:
  - repo: https://github.com/ambv/black
    rev: '23.7.0'
    hooks:
    - id: black
      language_version: python3.11
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    - id: mypy
      args: [--strict, --ignore-missing-imports, --install-types, --non-interactive]
      additional_dependencies: [tokenize-rt==3.2.0]
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
    -   id: flake8
